### PR TITLE
Test/demo00

### PR DESCRIPTION
**Pull request by nakayamanobuhiro**
Test for Developers.io day one demo

### CODE REVIEW

**Comment by nakayamanobuhiro** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by nakayamanobuhiro** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by nakayamanobuhiro** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by nakayamanobuhiro** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by nakayamanobuhiro** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by NobuhiroNakayama** [comment]
設定確認

**Pull request merged**
